services:
  - type: web
    name: n8n
    env: docker
    dockerfilePath: ./Dockerfile
    region: frankfurt
    plan: starter
    numInstances: 1
    healthCheckPath: /healthz
    envVars:
      - key: PORT
        value: "5678"
      - key: N8N_PORT
        value: "5678"
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_LOG_LEVEL
        value: debug
      - key: GENERIC_TIMEZONE
        value: Europe/Paris
      - key: TZ
        value: Europe/Paris
      - key: N8N_DEFAULT_LOCALE
        value: fr
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: WEBHOOK_URL
        value: https://n8n-a6u8.onrender.com
      - key: DB_POSTGRESDB_HOST
        value: 18.198.145.223
      - key: DB_POSTGRESDB_PORT
        value: "5432"
      - key: DB_POSTGRESDB_DATABASE
        value: postgres
      - key: DB_POSTGRESDB_USER
        value: postgres
      - key: DB_POSTGRESDB_PASSWORD
        sync: false
      - key: DB_POSTGRESDB_SSL_ENABLED
        value: "true"
      - key: DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED
        value: "false"
      - key: DB_POSTGRESDB_POOL_SIZE
        value: "2"
      - key: NODE_OPTIONS
        value: "--dns-result-order=ipv4first"
      - key: N8N_COOKIE_DOMAIN
        value: .onrender.com

  - type: web
    name: metabase
    env: docker
    dockerfilePath: ./metabase.Dockerfile
    region: frankfurt
    plan: free
    branch: main
    numInstances: 1
    healthCheckPath: /api/health
    envVars:
      - key: MB_DB_TYPE
        value: postgres
      - key: MB_DB_DBNAME
        value: postgres
      - key: MB_DB_PORT
        value: "5432"
      - key: MB_DB_HOST
        value: 18.198.145.223
      - key: MB_DB_USER
        value: postgres
      - key: MB_DB_PASS
        value: YjxBJtgTwSlBxnSQ
      - key: MB_SITE_URL
        value: https://metabase-a6u8.onrender.com
      - key: JAVA_OPTS
        value: "-Xmx750m"
      - key: PORT
        value: "3000"

      - key: PORT
        value: "3000"
